apiVersion: apps/v1
kind: Deployment
metadata:
  name: na-d
spec:
  selector:
    matchLabels:
      app: na-d
  replicas: 2
  template:
    metadata:
      labels:
        app: na-d 
    spec:
      containers:
      - name: na-d
        image: kartikeya532001/nodeapp_test:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        livenessProbe :
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe :
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 3
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
       
       
---
apiVersion: v1
kind: Service
metadata:
  name: na-s
spec:
  selector:
    app: na-d
  ports:
    - protocol: "TCP"
      port: 8000
      targetPort: 5000
  type: NodePort
